### ISSUE TITLE
Pull from (source) client instead of push to (target) server?

### ISSUE THREAD

**Issue by astrand** [magnetikonline/rsyncbackuprotation#2]
Would it be possible to setup rsyncbackuprotation to "pull" the stuff to backup from the client? Ie rsync/SSH executed on the (target) backup server.

**Comment by magnetikonline** [comment]
That would be pretty much it's own utility - as you would need to re-create Rsync's current magic where it hard links to identical files/etc. Since what you're doing is having Rsync pull from source (which itself would then need to be an Rsync module/source (not push) and then manage the incremental storage itself.

Maybe Rsync can do this out of the box - looking at the man page around `--link-dest` it seems possible - as the "dest" can be the local side.

E.g. from https://www.samba.org/ftp/rsync/rsync.html

```sh
rsync -av --link-dest=$PWD/prior_dir host:src_dir/ new_dir/
```

In this case it's pulling from a remote `host:src_dir/` to a local target and linking there.

Probably not something I could look at soon, but possibly an interesting alternative app. But it does mean all your source servers to "pull" from need to be setup as Rsync modules.
